server:
  port: 8000
  servlet:
    context-path: /calendar
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/Views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://snscalendar.crkseamzpghf.ap-northeast-2.rds.amazonaws.com:3306/callendar?serverTimezone=Asia/Seoul
    username: dmswl
    password: dmswl0818
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
      fail-on-empty-beans: false



